const assert = require("node:assert/strict");
global.btoa ||= value => Buffer.from(value, "binary").toString("base64");

(async () => {
  const { analyzeFoodImage, CLOUDFLARE_AI_MODEL, PHOTO_FOOD_PROMPT } = await import("../backend/src/cloudflare-ai-adapter.js");
  const { runProvider } = await import("../backend/src/index.js");
  const { safeLog } = await import("../backend/src/logging.js");
  const item = (name, confidence = .8) => ({ name, preparation: null, estimatedPortion: "normal", estimatedGrams: null, identityConfidence: confidence, quantityConfidence: .35, notes: ["Revisá la cantidad"] });
  const proposal = items => ({ schemaVersion: 1, items, unknownComponents: [], uncertainties: [] });
  let captured;
  const ai = { run: async (model, input) => { captured = { model, input }; return { answer: JSON.stringify(proposal([item("pollo"), item("arroz", .72)])), metrics: { input_tokens: 120, output_tokens: 60, neurons: 42 } }; } };
  const result = await analyzeFoodImage(new Uint8Array([0xff, 0xd8, 0xff]), { ai });
  assert.equal(result.model, CLOUDFLARE_AI_MODEL);
  assert.deepEqual(result.proposal.items.map(value => value.name), ["pollo", "arroz"]);
  assert.deepEqual(result.usage, { inputTokens: 120, outputTokens: 60, totalTokens: undefined, neurons: 42 });
  assert.equal(captured.model, "@cf/moondream/moondream3.1-9B-A2B");
  assert.match(captured.input.image, /^data:image\/jpeg;base64,/);
  assert.equal(captured.input.task, "query"); assert.equal(captured.input.reasoning, false);
  assert.match(PHOTO_FOOD_PROMPT, /No calcules calorias, proteinas, carbohidratos, grasas/);
  assert.equal(/historial|peso corporal|objetivos|identidad|gym/i.test(JSON.stringify(captured.input)), false);
  assert.equal(result.proposal.items.some(value => "calories" in value || "protein" in value || "carbs" in value || "fat" in value), false);
  assert.equal(result.proposal.items[0].estimatedGrams, null);
  const returns = answer => ({ run: async () => ({ answer }) });
  await assert.rejects(analyzeFoodImage(new Uint8Array([1]), { ai: returns(JSON.stringify(proposal([]))) }), /no_food_detected/);
  await assert.rejects(analyzeFoodImage(new Uint8Array([1]), { ai: returns("no-json") }), /provider_invalid_json/);
  await assert.rejects(analyzeFoodImage(new Uint8Array([1]), { ai: returns(JSON.stringify({ items: [] })) }), /invalid_provider_response/);
  await assert.rejects(analyzeFoodImage(new Uint8Array([1]), { ai: returns(JSON.stringify(proposal([item("posible comida", .3)]))) }), /low_confidence/);
  await assert.rejects(analyzeFoodImage(new Uint8Array([1]), { ai: returns(JSON.stringify({ ...proposal([item("pollo")]), calories: 200 })) }), /invalid_provider_response/);
  await assert.rejects(analyzeFoodImage(new Uint8Array([1]), {}), /cloudflare_ai_disabled/);
  await assert.rejects(analyzeFoodImage(new Uint8Array([1]), { ai: { run: async () => { throw new Error("model unavailable"); } } }), /provider_unavailable/);
  await assert.rejects(analyzeFoodImage(new Uint8Array([1]), { ai: { run: async () => { throw new Error("quota exceeded"); } } }), /provider_rate_limit/);
  const request = new Request("https://test");
  assert.equal((await runProvider("mock", new Uint8Array([1]), {}, request, "success")).model, "mock");
  assert.equal((await runProvider("cloudflare-ai", new Uint8Array([1]), { AI: ai }, request, "success")).model, CLOUDFLARE_AI_MODEL);
  await assert.rejects(runProvider("gemini", new Uint8Array([1]), {}, request, "success"), /gemini_disabled/);
  await assert.rejects(runProvider("unknown", new Uint8Array([1]), {}, request, "success"), /invalid_provider/);
  const abort = new AbortController();
  const pending = runProvider("cloudflare-ai", new Uint8Array([1]), { AI: { run: () => new Promise(() => {}) } }, new Request("https://test", { signal: abort.signal }), "success");
  abort.abort();
  await assert.rejects(pending, /timeout/, "timeout controlado");
  const logs = []; const safe = safeLog({ requestId: "id", provider: "cloudflare-ai", model: CLOUDFLARE_AI_MODEL, neurons: 42, image: "base64", response: proposal([item("pollo")]), foods: ["pollo"] }, { log: line => logs.push(line) });
  assert.deepEqual(Object.keys(safe).sort(), ["model", "neurons", "provider", "requestId"]);
  assert.equal(/base64|pollo|Revisá/.test(logs[0]), false);
  console.log("FORZA Cloudflare AI adapter tests: OK");
})().catch(error => { console.error(error); process.exitCode = 1; });
