const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const { webcrypto } = require("node:crypto");
const context = { console, crypto: webcrypto, Date, setTimeout, clearTimeout };
context.globalThis = context; context.window = context;
vm.runInNewContext(fs.readFileSync("smart-text-catalog.js", "utf8"), context);
vm.runInNewContext(fs.readFileSync("smart-text.js", "utf8"), context);
vm.runInNewContext(fs.readFileSync("nutrition-fallback.js", "utf8"), context);
const api = context.ForzaNutritionFallback;
assert.equal(api.STORAGE_KEY, "forza_nutrition_learned_foods");
assert.deepEqual(JSON.parse(JSON.stringify(api.sanitizeMemory({ broken: true }))), { schemaVersion: 1, updatedAt: null, foods: [] });
const unknown = text => ({ rawText: text, items: [], unrecognized: [text], totals: { calories: null, protein: null, carbs: null, fat: null }, questions: [] });
const parseQuantity = text => { const match = text.match(/(\d+)\s*g/); return match ? { grams: Number(match[1]) } : null; };
let calls = 0;
const estimate = async foods => { calls += 1; assert.equal(foods[0].label, "merluza"); return { foods: [{ clientRef: "u1", normalizedName: "Merluza", category: "fish", preparation: null, basis: "per_100g", calories: 90, protein: 18, carbs: 0, fat: 2, unitWeightGrams: null, confidenceBand: "medium" }] }; };
(async () => {
  const almond = context.ForzaSmartText.interpret("15 almendras");
  assert.equal(almond.unrecognized.length, 0, "catálogo oficial resuelve almendras");
  assert.equal(calls, 0, "catálogo oficial no usa memoria ni Gemini");
  const first = await api.resolve(unknown("150 g de merluza"), { memory: null, parseQuantity, estimate });
  assert.equal(calls, 1); assert.equal(first.result.items[0].fallbackKind, "estimated");
  assert.deepEqual(JSON.parse(JSON.stringify(first.result.totals)), { calories: 135, protein: 27, carbs: 0, fat: 3 });
  const learned = api.learn(first.memory, first.result, first.result.totals, new Date("2026-08-19T12:00:00Z"));
  assert.equal(learned.foods.length, 1); assert.equal(learned.foods[0].nutrition.calories, 90);
  const second = await api.resolve(unknown("200 g de merluza"), { memory: learned, parseQuantity, estimate });
  assert.equal(calls, 1, "memoria evita Gemini"); assert.equal(second.result.items[0].fallbackKind, "learned"); assert.equal(second.result.totals.calories, 180);
  const mixed = { ...first.result, items: [...first.result.items, { name: "Arroz", calories: 100, protein: 2, carbs: 20, fat: 1 }], unrecognized: [] };
  assert.equal(api.canLearn(mixed, { calories: 235, protein: 29, carbs: 20, fat: 4 }), false);
  assert.equal(api.canLearn(first.result, { calories: NaN, protein: 27, carbs: 0, fat: 3 }), false);
  assert.equal(api.sanitizeMemory({ schemaVersion: 1, foods: [{ bad: true }] }).foods.length, 0);
  const futureOfficial = { rawText: "200 g de merluza", items: [{ catalogId: "future-hake", name: "Merluza" }], unrecognized: [], totals: { calories: 160, protein: 34, carbs: 0, fat: 2 } };
  if (futureOfficial.unrecognized.length) await api.resolve(futureOfficial, { memory: learned, parseQuantity, estimate });
  assert.equal(calls, 1, "un futuro catálogo oficial gana sobre la memoria");
  console.log("FORZA Nutrition fallback frontend tests: OK");
})().catch(error => { console.error(error); process.exitCode = 1; });
